[project]
name = "python-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.6",
    "gunicorn>=23.0.0",
    "mysqlclient==2.2.7",
    "psycopg>=3.2",
    "whitenoise>=6.9.0",
]
